### ISSUE TITLE
Crash in get_passages() function call

### ISSUE THREAD

**Issue by anisha2102** [d223302/Merging-Facts-Crafting-Fallacies#1]
Hi,

Thank you for sharing your work. I tried running `factscore/factscorer_ambig.py` and I get the following error: `TypeError: get_passages() got multiple values for argument 'k'`. Can you please share any updates you may have done to the functions in `retriever.py`?

**Comment by d223302** [comment]
Sorry for the late reply; I didn't notice the issue. I forgot to push the `retriever.py`. I just added them and this should work. Thanks for noticing this. Please find it [here](https://github.com/d223302/Merging-Facts-Crafting-Fallacies/blob/main/FActScore/factscore/retrieval.py)
